export default {
  installation: "Installation",
  features: "Features",
  "getting-started": "Getting started",
  app: "App",
  "app-builder": "AppBuilder",
  blocks: "Blocks",
  api: "Api",
  addresses: "Addresses",
  storage: "Storage",
  bank: "Bank",
  staking: "Staking",
  distribution: "Distribution",
  governance: "Governance",
  stargate: "Stargate",
  wasm: "Wasm",
  custom: "Custom",
  ibc: "IBC",
};
