name: Check if links are valid

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  link-check:
    name: "Check if links are valid"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            link-inspector
      - name: Check all external links
        working-directory: ./link-inspector
        run: cargo run
